spring:
  profiles:
    active: local
    include: eureka

  datasource:
    url: jdbc:h2:mem:userDB
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    show_sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: create

server:
  port: 8081
