spring:
  profiles:
    active: local
---
spring:
  config:
    activate:
      on-profile: local
  application:
    name: user-service

  datasource:
    url: jdbc:h2:mem:userDB
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    show_sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true # hibernate 스키마 초기화 먼저 진행 - 이후 data.sql 반영하기 위함

  sql:
    init:
      mode: always

server:
  port: 8081

# eureka client 정보
eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:userDB
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    show_sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: create

# eureka client 정보
# 테스트 시, 유레카 클라이언트 설정 false
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false